spring:
  datasource:
    url: jdbc:mysql://localhost:3306/GymTrackerApp
    username: gymtracker
    password: gymtrackerpassword

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  thymeleaf:
    cache: false

  devtools:
    restart:
      exclude: "resources/static/**"
      
server:
  port: 8082
