spring:
  datasource:
    url: jdbc:mysql://localhost:3306/GymTrackerApp
    username: gymtracker
    password: gymtrackerpassword

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  thymeleaf:
    cache: false

